name: TheJumper
version: "0.1"
main: com.ariesninja.theJumper.TheJumper
api-version: "1.20"
commands:
  jumper:
    description: Core command for TheJumper
    usage: /<command> [start|stop|reset|join|leave|reload|setdiff|joinall|clearscore]
    permission: thejumper.use
  jumperhelp:
    description: Show TheJumper help book
    usage: /<command>
permissions:
  thejumper.use:
    default: true
  thejumper.admin:
    default: op
